config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  d_ssh:
    dst: ~/.ssh
    src: ssh
  f_bash_profile:
    dst: ~/.bash_profile
    link: nolink
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: nolink
    src: bashrc
  f_inputrc:
    dst: ~/.inputrc
    link: nolink
    src: inputrc
  f_profile:
    dst: ~/.profile
    link: nolink
    src: profile
  f_zshrc:
    dst: ~/.zshrc
    link: nolink
    src: zshrc
profiles:
  cinc225-213-dhcp.colorado.edu:
    dotfiles:
    - f_bash_profile
    - f_profile
    - f_bashrc
    - f_inputrc
    - f_zshrc
    - d_ssh
