config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
    link: true
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
    link: true
  f_inputrc:
    dst: ~/.inputrc
    src: inputrc
    link: true
  f_profile:
    dst: ~/.profile
    src: profile
    link: true
profiles:
  cinc225-213-dhcp.colorado.edu:
    dotfiles:
    - f_bash_profile
    - f_profile
    - f_bashrc
    - f_inputrc
